%% Housekeeping
 
addpath('ximu_matlab_library');	% include x-IMU MATLAB library
addpath('quaternion_library');	% include quatenrion library
close all;                     	% close all figures
clear;                         	% clear all variables
clc;                          	% clear the command terminal

%% Import data

xIMUdata = xIMUdataClass('LoggedData/LoggedData');

samplePeriod = 1/14;

gyr = [xIMUdata.CalInertialAndMagneticData.Gyroscope.X...
       xIMUdata.CalInertialAndMagneticData.Gyroscope.Y...
       xIMUdata.CalInertialAndMagneticData.Gyroscope.Z];        % gyroscope
acc = [xIMUdata.CalInertialAndMagneticData.Accelerometer.X...
       xIMUdata.CalInertialAndMagneticData.Accelerometer.Y...
       xIMUdata.CalInertialAndMagneticData.Accelerometer.Z];	% accelerometer

global fig

fig = uifigure('Position',[100 100 500 800]);

btn = uibutton(fig,'push',...
           'Text', 'RUN',...
           'Position',[50, 700, 100, 22],...
           'ButtonPushedFcn', @(btn,event) Plotting(event, avr, fig));

sld1 = uislider(fig,...
               'Position',[100 650 300 3],...
               'ValueChangedFcn',@(sld1,event) slider1Moving(sld1));
sld2 = uislider(fig,...
               'Position',[100 600 300 3],...
               'ValueChangedFcn',@(sld2,event) slider2Moving(sld2));
sld3 = uislider(fig,...
               'Position',[100 550 300 3],...
               'ValueChangedFcn',@(sld3,event) slider3Moving(sld3));
sld4 = uislider(fig,...
               'Position',[100 500 160 3],...
               'ValueChangedFcn',@(sld4,event) slider4Moving(sld4));


sld1.Limits = [0 30];
sld2.Limits = [0 30];
sld3.Limits = [0 30];
sld4.Limits = [0 30];

label1 = uilabel(fig,...
'Position',[20 640 50 15],...
'Text','Kp');

label2 = uilabel(fig,...
'Position',[20 590 50 15],...
'Text','Ki');

label3 = uilabel(fig,...
'Position',[20 540 50 15],...
'Text','Cutoff frequency of linear velocity');

label4 = uilabel(fig,...
'Position',[20 490 50 15],...
'Text','Cutoff frequency of position');

